### ISSUE TITLE
intro.js for bootstrap modal Example (Done)

### ISSUE THREAD

**Issue by kouroshsalahshoor** [usablica/intro.js#302]
Does anyone have a working example for intro.js working with Bootstrap Modals?

**Comment by silentFred** [comment]
@kourosh23 what changes did you guys make to get this to work?

**Comment by brunocechet** [comment]
Explain please!

**Comment by bytebrain** [comment]
I've got a fix for 1.1.1 and higher. I've posted on later issue https://github.com/usablica/intro.js/issues/485 this:

I've fixed it. I've added this to my css, and moves all **modal elements at the end of the** `<body>` and not in any child element, or else all you'll get strange positioning.

```css
.introjs-fixParent.modal,
.introjs-fixParent.modal-dialog {
  position: relative !important;  
}
```

Fixed my modals with this:
```js
$(document).ready(function(){
    $('div.modal').appendTo('body');
});
```
