### ISSUE TITLE
the option disableInteraction property do not work.

### ISSUE THREAD

**Issue by rockcoder23** [usablica/intro.js#397]
I saw the introjs.css file has code blow:

1. the style of the element be highlight.
```css
.introjs-showElement,
tr.introjs-showElement > td,
tr.introjs-showElement > th {
      z-index: 9999999 !important;
}
```
2. the property disableInteraction style codes:
```css
.introjs-disableInteraction {
  z-index: 99999999 !important;
  position: absolute;
}
```

3. the tooltipRefrenceLayer style codes:

```css
.introjs-tooltipReferenceLayer {
  position: absolute;
  z-index: 10000000;
}
```
so, I change the z-index value(maybe 1000000) of  tooltipReferenceLayer less than the  highlight element's z-index value, it works!
