### ISSUE TITLE
the introjs-fixParent class has a small problem.

### ISSUE THREAD

**Issue by rockcoder23** [usablica/intro.js#400]
the source code  like below: 

``` css
.introjs-fixParent {
  z-index: auto !important;
  opacity: 1.0 !important;
  position: absolute !important;
  -webkit-transform: none !important;
     -moz-transform: none !important;
      -ms-transform: none !important;
       -o-transform: none !important;
          transform: none !important;
}
```
1. the susiation in my project is I have header of page positioned with 'fixed' and 'z-index' value is 10.  when I use introjs to highlight a child element of header,  the header  is added the class introjs-fixParent. then, the header  goes to ruin  in IE 8.  Because the header position override to absolute.
2. so I remove `position: absolute !important;` IE 8 has been fixed, but another problem came. the element didn't be highlight in chrome. Because in chrome 22+  the position  fixed will form  a new  stacking context . (https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context)
3.  at last,  I change the code like below:

``` css
@media screen and (-webkit-min-device-pixel-ratio:0) {
  .introjs-fixParent {
    position: absolute !important;
  }
}
.introjs-fixParent {
  z-index: auto !important;
  opacity: 1.0 !important;
  -webkit-transform: none !important;
     -moz-transform: none !important;
      -ms-transform: none !important;
       -o-transform: none !important;
          transform: none !important;
}
```
