### ISSUE TITLE
Option to Remove/Edit Helper Padding

### ISSUE THREAD

**Issue by BrianLaughlan** [usablica/intro.js#509]
By default there is a 10px fixed padding value on the helper layer. When we want to highlight a section that is touching the edge of the screen like e.g. a side column, then the padding and borders on the helpers might cause problems with the layout. **It would be great to make padding and helper styling configurable, so we can remove or modify it.**

A work around function can be seen below for people who want to do this but don't want to modify the core plugin. It can be called after the step has started.

```javascript
function removeHelperPadding() {
    var helpers = $('.introjs-helperLayer, .introjs-tooltipReferenceLayer'),
        newHeight = helpers.height() - 10,
        newWidth  = helpers.width() - 10,
        newTop    = parseInt(helpers.css('top')) + 5,
        newLeft   = parseInt(helpers.css('left')) + 5;

    helpers.css({
      'height': newHeight,
      'width' : newWidth,
      'top'   : newTop,
      'left'  : newLeft
    });
  }
```

You must call the function after the start(); but it should also remove the padding on every step after that as well...

```javascript
intro.onafterchange(function() {
   removeHelperPadding();
});
```

Note: Because the size of the helper is modified after it is drawn, the css transition shows the change. I removed the transitions and styling of the helper (which I actually prefer anyway, less busy). 

```css
.introjs-helperLayer,
.introjs-tooltipReferenceLayer {
    transition: none !important;
}

.introjs-helperLayer {
    background-color: none !important;
    border: none !important;
    border-radius: 0 !important;
    box-shadow: none !important;
}
```
