### ISSUE TITLE
Consider using introJS.scss

### ISSUE THREAD

**Issue by danmv** [usablica/intro.js#529]
It will be really cool and helpful to have Sass files for the css. It will make it really easy to change templates and create new ones.

**Comment by Anahkiasen** [comment]
:+1: for this, would make it a lot easier to theme

**Comment by bozdoz** [comment]
Definitely could.  I also think [autoprefixer](https://github.com/postcss/autoprefixer) would help reduce the source files, so we wouldn't have to write all the compatibility prefixes.  I could see this as part of modularization too, #666. We could have simple theme files that adjust variables, something like:

```scss
/* introjs-dark.scss */
$bg_color: #fff;
import 'introjs';
```

and the main file

```scss
/* introjs.scss */
$bg_color: #000 !default;

.introjs-overlay {
  background-color: $bg_color;
}
```
