### ISSUE TITLE
Is it possible to disable Prev Button during the whole tour ? 

### ISSUE THREAD

**Issue by cammilleLe** [usablica/intro.js#740]
Hi everyone,

I'm looking for the best way to disable the Prev button.

**Comment by bozdoz** [comment]
Could do CSS:

```css
.introjs-prevbutton {
  display:none;
}
```
